# Generated by Django 3.1.4 on 2020-12-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EOD_prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('date', models.DateField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stocks')),
            ],
        ),
    ]
