# Generated by Django 3.1.4 on 2021-01-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='chart',
        ),
    ]
